package calculadora;

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class CalculadoraDerivada extends javax.swing.JFrame {

    private boolean punto = true; //sirve para el punto
    String valor1, valor2, signo, contenido;
    Double resultado;
    BufferedImage image;
    UtilsX obj = new UtilsX();

    public CalculadoraDerivada() {
        initComponents();
        this.setTitle("CALCULADORA P.FINAL");
        this.setLocationRelativeTo(null);
        try {
            image = ImageIO.read(obj.getFile("icon1.png"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        this.setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFunction = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        brtmenos = new javax.swing.JButton();
        btnmas = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnelev = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btnparen1 = new javax.swing.JButton();
        btnparen2 = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnpi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtsegundaderivada = new javax.swing.JTextField();
        btnDerivar = new javax.swing.JButton();
        txtFuncionSalida = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setText("Funcion A derivar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        txtFunction.setBackground(new java.awt.Color(0, 0, 0));
        txtFunction.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        txtFunction.setForeground(new java.awt.Color(51, 255, 51));
        txtFunction.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFunctionActionPerformed(evt);
            }
        });
        getContentPane().add(txtFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 29, 436, 50));

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7number_7_3074.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-7-icon_34776.png"))); // NOI18N
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-7-icon_34776.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8number_8_3824.png"))); // NOI18N
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-8-icon_34775.png"))); // NOI18N
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-8-icon_34775.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9number_9_3071.png"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-9-icon_34774.png"))); // NOI18N
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-9-icon_34774.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btndel.setBorderPainted(false);
        btndel.setContentAreaFilled(false);
        btndel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elim.png"))); // NOI18N
        btndel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elim.png"))); // NOI18N
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4number_4_3829 (1).png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-4-icon_34779.png"))); // NOI18N
        btn4.setRequestFocusEnabled(false);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-4-icon_34779.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_number_3827.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-5-icon_34778.png"))); // NOI18N
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-5-icon_34778.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6_number_3075.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-6-icon_34777.png"))); // NOI18N
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-6-icon_34777.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        btnx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.setBorderPainted(false);
        btnx.setContentAreaFilled(false);
        btnx.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });
        getContentPane().add(btnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        btndiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/division_box_icon_137684.png"))); // NOI18N
        btndiv.setBorderPainted(false);
        btndiv.setContentAreaFilled(false);
        btndiv.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486505258-divide-division-dote-square_81435.png"))); // NOI18N
        btndiv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486505258-divide-division-dote-square_81435.png"))); // NOI18N
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });
        getContentPane().add(btndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        brtmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minus-gross-horizontal-straight-line-symbol_icon-icons.com_74137.png"))); // NOI18N
        brtmenos.setToolTipText("");
        brtmenos.setBorderPainted(false);
        brtmenos.setContentAreaFilled(false);
        brtmenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486504817-delete-minus-cancel-exit-remove_81373.png"))); // NOI18N
        brtmenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486504817-delete-minus-cancel-exit-remove_81373.png"))); // NOI18N
        brtmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtmenosActionPerformed(evt);
            }
        });
        getContentPane().add(brtmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 42, -1));

        btnmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_icon-icons.com_74429.png"))); // NOI18N
        btnmas.setBorderPainted(false);
        btnmas.setContentAreaFilled(false);
        btnmas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus_40632.png"))); // NOI18N
        btnmas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus_40632.png"))); // NOI18N
        btnmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasActionPerformed(evt);
            }
        });
        getContentPane().add(btnmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2number_2_3079 (1).png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-2-icon_34781 (1).png"))); // NOI18N
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-2-icon_34781 (1).png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3number_3_3077 (1).png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-3-icon_34780 (1).png"))); // NOI18N
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-3-icon_34780 (1).png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1number_1_3831 (1).png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-1-icon_34782 (1).png"))); // NOI18N
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-1-icon_34782 (1).png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnpunto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnpunto.setText(".");
        btnpunto.setBorderPainted(false);
        btnpunto.setContentAreaFilled(false);
        btnpunto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N
        btnpunto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 69, 40));

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-0-icon_34783.png"))); // NOI18N
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-0-icon_34783.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        btncos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.setBorderPainted(false);
        btncos.setContentAreaFilled(false);
        btncos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });
        getContentPane().add(btncos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnsin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.setBorderPainted(false);
        btnsin.setContentAreaFilled(false);
        btnsin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });
        getContentPane().add(btnsin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        btnigual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.setToolTipText("");
        btnigual.setBorderPainted(false);
        btnigual.setContentAreaFilled(false);
        btnigual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        getContentPane().add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        btntan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.setBorderPainted(false);
        btntan.setContentAreaFilled(false);
        btntan.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });
        getContentPane().add(btntan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        btnelev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.setBorderPainted(false);
        btnelev.setContentAreaFilled(false);
        btnelev.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelevActionPerformed(evt);
            }
        });
        getContentPane().add(btnelev, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        btnraiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.setBorderPainted(false);
        btnraiz.setContentAreaFilled(false);
        btnraiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizActionPerformed(evt);
            }
        });
        getContentPane().add(btnraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        btnparen1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnparen1.setText("(");
        btnparen1.setToolTipText("");
        btnparen1.setBorderPainted(false);
        btnparen1.setContentAreaFilled(false);
        btnparen1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparen1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnparen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 60, 57));

        btnparen2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnparen2.setText(")");
        btnparen2.setBorderPainted(false);
        btnparen2.setContentAreaFilled(false);
        btnparen2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparen2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnparen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 62, 57));

        btnlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_log_icon_135415.png"))); // NOI18N
        btnlog.setBorderPainted(false);
        btnlog.setContentAreaFilled(false);
        btnlog.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_29907.png"))); // NOI18N
        btnlog.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_29907.png"))); // NOI18N
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        btnpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.setBorderPainted(false);
        btnpi.setContentAreaFilled(false);
        btnpi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpiActionPerformed(evt);
            }
        });
        getContentPane().add(btnpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton1.setText("+/-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 73, -1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ejemplos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 158, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Derivada Logaritmica");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 346, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Derivada Exponencial");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 346, -1));

        jButton2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton2.setText("f(x) = e^x-x");
        jButton2.setActionCommand("f'(x) = e^x-x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jButton3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton3.setText("f(x) = log (3x^2-2x+1)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 580, 400));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setText("Funcion derivada:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 260, 254, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 360, 400));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButton4.setText("ACELERACION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 160, 50));

        txtsegundaderivada.setBackground(new java.awt.Color(102, 102, 102));
        txtsegundaderivada.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtsegundaderivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsegundaderivadaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsegundaderivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 380, 50));

        btnDerivar.setBackground(new java.awt.Color(204, 255, 204));
        btnDerivar.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnDerivar.setText("VELOCIDAD");
        btnDerivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDerivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 52));

        txtFuncionSalida.setBackground(new java.awt.Color(102, 102, 102));
        txtFuncionSalida.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtFuncionSalida.setForeground(new java.awt.Color(0, 255, 51));
        txtFuncionSalida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFuncionSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFuncionSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 390, 50));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Info.");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncionSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncionSalidaActionPerformed

    private void btnDerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivarActionPerformed
        String funcion = txtFunction.getText();
        Derivadas derivada = new Derivadas();
        derivada.setFuncionADerivar(funcion);
        derivada.derivar();
        txtFuncionSalida.setText(derivada.getFuncionDerivada());

        if (!funcion.isEmpty()) {
            derivada = new Derivadas();
            derivada.setFuncionADerivar(funcion);
            derivada.derivar();
            txtFuncionSalida.setText(derivada.getFuncionDerivada());
        } else {
            JOptionPane.showMessageDialog(null, "Campo vacio. \nIngrese una funcion", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDerivarActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txtFunction.setText(txtFunction.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnelevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelevActionPerformed
        txtFunction.setText(txtFunction.getText() + "^");
// TODO add your handling code here:
    }//GEN-LAST:event_btnelevActionPerformed

    private void btnmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasActionPerformed
        txtFunction.setText(txtFunction.getText() + "+");
    }//GEN-LAST:event_btnmasActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtFunction.setText(txtFunction.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        contenido = txtFunction.getText();
        //contenido menor o igual a 0, muestra "o"
        //si el campo está vacio muestra "0."
        if (contenido.length() <= 0) {
            txtFunction.setText("0.");
        } else //contamos cuantos puntos existen, si existe un punto,
        //no podra colocarse otro punto
        if (txtFunction.getText().contains(".")) {
        } else {
            txtFunction.setText(txtFunction.getText() + ".");
            punto = false;

        }
    }//GEN-LAST:event_btnpuntoActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        txtFunction.setText(txtFunction.getText() + "sin");
    }//GEN-LAST:event_btnsinActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        txtFunction.setText(txtFunction.getText() + "cos");
    }//GEN-LAST:event_btncosActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        txtFunction.setText(txtFunction.getText() + "=");
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnparen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparen1ActionPerformed
        txtFunction.setText(txtFunction.getText() + "(");
    }//GEN-LAST:event_btnparen1ActionPerformed

    private void btnparen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparen2ActionPerformed
        txtFunction.setText(txtFunction.getText() + ")");
    }//GEN-LAST:event_btnparen2ActionPerformed

    private void btnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizActionPerformed
        txtFunction.setText(txtFunction.getText() + "sqrt(");
    }//GEN-LAST:event_btnraizActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        txtFunction.setText("");
        txtFuncionSalida.setText("");
        txtsegundaderivada.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtFunction.setText(txtFunction.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        txtFunction.setText(txtFunction.getText() + "tan");
    }//GEN-LAST:event_btntanActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        txtFunction.setText(txtFunction.getText() + "log");
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpiActionPerformed
        txtFunction.setText(txtFunction.getText() + "3.1416");
    }//GEN-LAST:event_btnpiActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtFunction.setText(txtFunction.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtFunction.setText(txtFunction.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void brtmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtmenosActionPerformed
        txtFunction.setText(txtFunction.getText() + "-");
    }//GEN-LAST:event_brtmenosActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtFunction.setText(txtFunction.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txtFunction.setText(txtFunction.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtFunction.setText(txtFunction.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        txtFunction.setText(txtFunction.getText() + "*");
    }//GEN-LAST:event_btnxActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        txtFunction.setText(txtFunction.getText() + "/");
    }//GEN-LAST:event_btndivActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txtFunction.setText(txtFunction.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtFunction.setText(txtFunction.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contenido = txtFunction.getText();
        if (contenido.length() > 0) {
            resultado = (-1) * Double.parseDouble(contenido);
            txtFunction.setText(resultado.toString());
            //Multiplicamoes el -1 para convertir un numero a positivo o negativo
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed

        //Boton borrar
        contenido = txtFunction.getText();
        if (contenido.length() > 0) {
            contenido = contenido.substring(0, contenido.length() - 1);
            txtFunction.setText(contenido);
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtFunction.setText("e^x-x");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtFunction.setText("log(3x^2-2x+1)");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFunctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFunctionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String funcion = txtFuncionSalida.getText();
        Derivadas derivada = new Derivadas();
        derivada.setFuncionADerivar(funcion);
        derivada.derivar();
        txtsegundaderivada.setText(derivada.getFuncionDerivada());

        if (!funcion.isEmpty()) {
            derivada = new Derivadas();
            derivada.setFuncionADerivar(funcion);
            derivada.derivar();
            txtFuncionSalida.setText(derivada.getFuncionDerivada());
        } else {
            JOptionPane.showMessageDialog(null, "Campo vacio. \nHalle la velocidad primero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtsegundaderivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsegundaderivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsegundaderivadaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "PRESENTACION DEL PROYECTO FINAL.\nDesarrollado por: Daniel Ccana Y Yho jana Uscamayta"
                + "\nFELIZ NAVIDAD Y UN PROSPERO AÑO NUEVO", "Presentacion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtmenos;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDerivar;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnelev;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmas;
    private javax.swing.JButton btnparen1;
    private javax.swing.JButton btnparen2;
    private javax.swing.JButton btnpi;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFuncionSalida;
    private javax.swing.JTextField txtFunction;
    private javax.swing.JTextField txtsegundaderivada;
    // End of variables declaration//GEN-END:variables
}
